`timescale 1ns/1ps

module fc1_weight_mem (
    input  wire [11:0] addr,

    output wire signed [7:0] weight0,
    output wire signed [7:0] weight1,
    output wire signed [7:0] weight2,
    output wire signed [7:0] weight3,
    output wire signed [7:0] weight4,
    output wire signed [7:0] weight5,
    output wire signed [7:0] weight6,
    output wire signed [7:0] weight7
);

    // --------------------------------------------------------
    // Eight logical weight banks
    //
    // Each bank contains:
    //   4 neurons × 784 inputs = 3136 weights
    //
    // Bank 0 → neurons 0, 8, 16, 24
    // Bank 1 → neurons 1, 9, 17, 25
    // ...
    // Bank 7 → neurons 7, 15, 23, 31
    // --------------------------------------------------------

    reg signed [7:0] bank0 [0:3135];
    reg signed [7:0] bank1 [0:3135];
    reg signed [7:0] bank2 [0:3135];
    reg signed [7:0] bank3 [0:3135];
    reg signed [7:0] bank4 [0:3135];
    reg signed [7:0] bank5 [0:3135];
    reg signed [7:0] bank6 [0:3135];
    reg signed [7:0] bank7 [0:3135];


    // --------------------------------------------------------
    // Load quantized FC1 weights generated by Python
    // --------------------------------------------------------

    initial begin
    $readmemh("data/fc1_bank0.mem", bank0);
    $readmemh("data/fc1_bank1.mem", bank1);
    $readmemh("data/fc1_bank2.mem", bank2);
    $readmemh("data/fc1_bank3.mem", bank3);
    $readmemh("data/fc1_bank4.mem", bank4);
    $readmemh("data/fc1_bank5.mem", bank5);
    $readmemh("data/fc1_bank6.mem", bank6);
    $readmemh("data/fc1_bank7.mem", bank7);
end


    // --------------------------------------------------------
    // Eight parallel weight outputs
    // --------------------------------------------------------

    assign weight0 = bank0[addr];
    assign weight1 = bank1[addr];
    assign weight2 = bank2[addr];
    assign weight3 = bank3[addr];
    assign weight4 = bank4[addr];
    assign weight5 = bank5[addr];
    assign weight6 = bank6[addr];
    assign weight7 = bank7[addr];

endmodule
